# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-docker-image:
    machine: true
    woring-directory: ~/repo
    steps:
      # build docker image
      - checkout
      - run: docker build -t sommerlan .
      - run: docker tag sommerlan anno1337/sommerlan:latest
      - run: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run: docker push anno1337/sommerlan:latest
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cc:b8:aa:6f:50:74:3c:b7:85:e7:6e:11:77:60:e7:3c"
      - attach_workspace:
          at: ~/tmp/repo
      - run: ssh anno1337@anno1337.com '/home/fjoggs/scripts/continous-deployment-sommerlan-koa.sh'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-docker-image
      - deploy:
          requires:
            - build-docker-image
          filters:
            branches:
              only: 
                - master
