# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-docker-image:
    machine: true
    woring-directory: ~/repo
    steps:
      # build docker image
      - checkout
      - run: docker build -t sommerlan .
      - run: docker tag sommerlan fjoggs/sommerlan:latest
      - run: echo "$DOCKER_PASS" docker login -u $DOCKER_USER --password-stdin
      - run: docker push anno1337/sommerlan:latest
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0a:2b:71:79:5b:9d:0a:9e:3e:2f:d7:23:9f:63:2c:29"
      - attach_workspace:
          at: ~/tmp/repo
      - run: ssh fjoggs@anno1337.com '/home/fjoggs/scripts/continous-deployment-sommerlan-koa.sh'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-docker-image
      - deploy:
          requires:
            - build-docker-image
          filters:
            branches:
              only: 
                - master
